merge with dev-metrics and webhook integration

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -105,7 +105,21 @@ jobs:
                 with:
                     name: trivy-report
                     path: trivy-report.sarif
+              
+            # Fail if critical vulnerabilities are found   
+            -   name: Analyze Trivy Results
+                run: |
+                    if grep -q '"CRITICAL"' trivy-report.json; then
+                        echo "Critical vulnerabilities found!"
+                        exit 1
+                    fi
 
+            # Notify when fail 
+            -   name: Notify via Webhook
+                if: failure()
+                run: |
+                    curl -X POST -H 'Content-type: application/json' --data '{"text":"⚠️ Vulnérabilités critiques détectées ⚠️}' ${{ secrets.DISCORD_WEBHOOK_URL  }}        
+                
     # minikube en local pour l'instant, aks prob à revoir si non possible prof donne accès pour déployer sur son serveur
     # deploy:
     #     runs-on: ubuntu-latest
